### ISSUE TITLE
求大物实验报告

### ISSUE THREAD

**Issue by Eijiurus** [Sakura-shem/JLU-OpenAuto#3]
今年大二，跪求学长大物实验报告。＞﹏＜ 
Orz

**Comment by jlshen025** [comment]
物理报告我帮你问了下，都是纸质版本交的，大家都没留存。
（如果你今年愿意的话可以留存然后放到仓库里面，造福百姓。）

**Comment by Eijiurus** [comment]
> 物理报告我帮你问了下，都是纸质版本交的，大家都没留存。 （如果你今年愿意的话可以留存然后放到仓库里面，造福百姓。）

好的，我要是今年这门课得了优的话会 pull request 的 (✿◠‿◠)
